
#pragma once

#define VIAL_KEYBOARD_UID {0x8C, 0x59, 0x2E, 0xF7, 0xBA, 0x40, 0xCC, 0xCA}

#define ENCODERS_PAD_A { D4, F4 }
#define ENCODERS_PAD_B { C6, F5 }

#define VIAL_COMBO_ENTRIES 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 14 }
#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, KC_MPRV, KC_MNXT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }

// Typehud configuration
#define TYPEHUD_FILLGRAPH
#define TYPEHUD_MATRIX_COLS 15
#define TYPEHUD_MATRIX_COL_SHIFT 0
// #define TYPEHUD_MATRIX_ROTATE_90
// #define TYPEHUD_MATRIX_ROTATE_180
// #define TYPEHUD_MATRIX_ROTATE_270
